export const environment = {
    production: true,
    t2y12PruGU9wUtEGzBJfolMIgK: 'PAY:T-ANA:T-ACT:T-TRI:T-GRO:T-DEP:T-OPH:T-MTL:T-DGF:T-NAT:T-CAR:T-V1L:T-PSA:T-MTT:T-SUP:T-LBS:T-APP:T-DEV:T-NOT:T-RAS:T',
    VERSION: require('../../package.json').version,
    widgetUrl: 'https://tiledesk-server-production.up.railway.app/v4/launch.js',
    botcredendialsURL: 'CHANGE-IT',
    remoteConfig: false, 
    remoteConfigUrl: './dashboard-config.json',
    SERVER_BASE_URL: 'https://tiledesk-server-production.up.railway.app/',
    CHAT_BASE_URL: '../chat/',
    REST_API_BASE_URL: 'https://tiledesk-server-production.up.railway.app/v3/',
    CHAT_ENGINE_BASE_URL: 'https://tiledesk-server-production.up.railway.app',
    testsiteBaseUrl: 'https://tiledesk-server-production.up.railway.app/v2/widgets/test/load',
    wsUrl: 'wss://tiledesk-server-production.up.railway.app/v2/ws/',
    chatEngine: 'mqtt',
    firebaseAuth: false,
    uploadEngine: 'native', 
    baseImageUrl: "CHANGEIT",
    pushEngine: 'none',
    logLevel: 'Info',
    templatesUrl: 'CHANGEIT',
    appsUrl: 'CHANGEIT',
    promoBannerUrl: 'CHANGEIT',
    chatStoragePrefix: "CHANGEIT",
    firebase: {
        apiKey: "CHANGE-IT",
        authDomain: "CHANGE-IT",
        databaseURL: "CHANGE-IT",
        projectId: "CHANGE-IT",
        storageBucket: "CHANGE-IT",
        messagingSenderId: "CHANGE-IT",
        appId: 'CHANGEIT',
        vapidKey: 'CHANGEIT'
    },
};

